# Nama Worker Anda (bisa diganti)
name = "viora"

# File utama skrip Anda. Ganti "index.js" jika nama file Anda berbeda.
main = "_worker.js"

# Tanggal kompatibilitas (gunakan tanggal hari ini)
compatibility_date = "2025-09-10"
